start1:
	dotnet run WineSales.csproj --urls "http://host.docker.internal:5551"

start2:
	dotnet run WineSales.csproj --urls "http://host.docker.internal:5552"
	
start3:
	dotnet run WineSales.csproj --urls "http://host.docker.internal:5553"
	
start-mirror:
	dotnet run WineSales.csproj --urls "http://host.docker.internal:5555"

start:
	dotnet run WineSales.csproj --urls "http://host.docker.internal:5555"